ktor:
    application:
        modules:
            - example.com.ApplicationKt.module
    deployment:
        port: 8080
jwt:
  domain: "http://0.0.0.0:8080"
  audience: "jwt-audience"
  realm: "rocky-api"
